codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        # Fail the build if coverage drops by more than 1%
        threshold: 1%
        informational: true  # Don't fail the build on coverage issues
    patch:
      default:
        informational: true  # Don't fail the build on patch coverage

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "tests/**/*"
  - "setup.py"
  - "**/__init__.py"