# Jekyll configuration for GitHub Pages
title: TritonML
description: Deploy ML Models to Production in Minutes
url: https://aanshshah.github.io
baseurl: /tritonml

# Theme
theme: null

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
twitter:
  card: summary_large_image
  username: aanshshah

# Social
social:
  name: TritonML
  links:
    - https://github.com/aanshshah/tritonml

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor